name: Deploy to shinyapps.io

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.0'
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev
      
      - name: Install R packages
        run: |
          install.packages('rsconnect', repos='https://cloud.r-project.org/')
          install.packages('shiny', repos='https://cloud.r-project.org/')
        shell: Rscript {0}
      
      - name: Deploy to shinyapps.io
        env:
          SHINY_ACC_NAME: ${{ secrets.SHINY_ACC_NAME }}
          TOKEN: ${{ secrets.TOKEN }}
          SECRET: ${{ secrets.SECRET }}
        run: |
          library(rsconnect)
          setAccountInfo(
            name = Sys.getenv("SHINY_ACC_NAME"),
            token = Sys.getenv("TOKEN"),
            secret = Sys.getenv("SECRET")
          )
          deployApp(appDir = ".")
        shell: Rscript {0}
